favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.5053763
  lightness: 0.4390681
  brandColors:
    - '#0D0C0A'
    - '#797C8B'
    - '#9D9CA2'
    - '#F6A263'
    - '#5D5A57'
  rhythmicContrast: 0.3924731
typography_spectrum: 0.1218638
layout_spectrum: 0.3064516
cta:
  bucket: null
  version: null
  domain: null
name: Drew Palmer Photo
