favicon: null
name: Drew Palmer Photo
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.128342256648466
  brandStrength: 0.9566971657332033
  rhythmicContrast: 0.1032129053492099
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.3737157064024359
typography_spectrum: 0.5555201957467943
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3064516
analytics:
  twitter: null
  google: null
  facebook: null
