name: Drew Palmer Photo
favicon: null
layout_spectrum: 0.30830292054452
typography_spectrum: 0.5555201957467943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9566971657332033
  lightness: 0.3737157064024359
  saturation: 0.128342256648466
  rhythmicContrast: 0.1032129053492099
purpose: []
